plugins:
  - jest
env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
  - "plugin:prettier/recommended"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-continue: off
